import { useState } from 'react';
import { MessageSquare, Phone } from 'lucide-react';

interface MessagePanelProps {
  whatsappMessage: string;
  smsMessage: string;
  onWhatsappChange: (msg: string) => void;
  onSmsChange: (msg: string) => void;
}

const WA_MAX = 1000;
const SMS_MAX = 320;
const smsParts = (len: number) => Math.max(1, Math.ceil(len / 160));

function MessageCard({
  title,
  icon,
  value,
  onChange,
  max,
  placeholder,
  footer,
}: {
  title: string;
  icon: React.ReactNode;
  value: string;
  onChange: (v: string) => void;
  max: number;
  placeholder: string;
  footer?: React.ReactNode;
}) {
  const [useDefault, setUseDefault] = useState(false);

  const handleToggle = (checked: boolean) => {
    setUseDefault(checked);
    if (checked) onChange('');
  };

  return (
    <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5 flex flex-col gap-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          {icon}
          <h3 className="text-sm font-semibold text-gray-900">{title}</h3>
        </div>
        <label className="flex items-center gap-1.5 text-xs text-gray-500 cursor-pointer select-none">
          <input
            type="checkbox"
            checked={useDefault}
            onChange={(e) => handleToggle(e.target.checked)}
            className="rounded"
          />
          Use default message
        </label>
      </div>
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value.slice(0, max))}
        disabled={useDefault}
        placeholder={useDefault ? '(auto-generated by backend)' : placeholder}
        rows={5}
        className="w-full text-sm border border-gray-300 rounded-lg p-3 focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none disabled:bg-gray-50 disabled:text-gray-400"
      />
      <div className="flex items-center justify-between text-xs text-gray-400">
        <span className={value.length > max * 0.9 ? 'text-orange-500' : ''}>
          {value.length} / {max} chars
        </span>
        {footer}
      </div>
    </div>
  );
}

export default function MessagePanel({ whatsappMessage, smsMessage, onWhatsappChange, onSmsChange }: MessagePanelProps) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
      <MessageCard
        title="WhatsApp Message"
        icon={<MessageSquare size={16} className="text-green-600" />}
        value={whatsappMessage}
        onChange={onWhatsappChange}
        max={WA_MAX}
        placeholder="Hi {ownerName}! We'd like to discuss your shop {shopName}…"
      />
      <MessageCard
        title="SMS Message"
        icon={<Phone size={16} className="text-blue-600" />}
        value={smsMessage}
        onChange={onSmsChange}
        max={SMS_MAX}
        placeholder="হ্যালো! আপনার শপ সম্পর্কে আমরা কথা বলতে চাই…"
        footer={
          smsMessage.length > 0 ? (
            <span>{smsParts(smsMessage.length)} SMS part{smsParts(smsMessage.length) > 1 ? 's' : ''}</span>
          ) : null
        }
      />
    </div>
  );
}
